<?php

/**
 * Implementation of hook_help().
 *
 * The text is dummy. Only for test help messages.
 *
 */
function themetest_help($path, $arg) {
  switch ($path) {
    case 'themetest':
      return '<p>' . t('Help message for Theme Test module') . '</p>';
    case 'themetest/tab3':
      return '<p>' . t('Help message for Theme Test module: <strong>Lorem ipsum dolor sit amet</strong>, consectetur adipiscing elit. Fusce eget sapien arcu, sed cursus turpis. Fusce sed convallis metus. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem.') . '</p>';
  }
}

/**
 * Implementation of hook_init().
 */
function themetest_menu() {
  $items = array();
  $items['themetest'] = array(
    'title' => 'Theme Test',
    'page callback' => 'themetest_page',
    'access arguments' => array('access content'),
  );
  $items['themetest/tab1'] = array(
    'title' => 'Tab 1',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['themetest/tab2'] = array(
    'title' => 'Tab 2',
    'page callback' => 'themetest_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['themetest/tab3'] = array(
    'title' => 'Tab 3',
    'page callback' => 'themetest_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['themetest/form'] = array(
    'title' => 'Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('themetest_form_test'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['themetest/table'] = array(
    'title' => 'Table',
    'page callback' => 'themetest_table',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['themetest/table/%'] = array(
    'title' => 'Table',
    'page callback' => 'themetest_table',
    'page arguments' => array(2, 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'weight' => 1,
  );
  $items['themetest/table/%/%'] = array(
    'title' => 'Table',
    'page callback' => 'themetest_table',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'weight' => 1,
  );
  return $items;
}

/**
 * Page for three tab page. Included three type of messages, help, breadcrumb,
 * HTML and pager
 */

function themetest_page() {
// Try breadcrumb
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Tab 1', 'themetest');
  if (arg(1) == 'tab2' || arg(1) == 'tab3' ) {
    $breadcrumb[] = l('Tab 2', 'themetest/tab2');
  }
  if (arg(1) == 'tab3' ) {
    $breadcrumb[] = l('Tab 3', 'themetest/tab3');
  }
  drupal_set_breadcrumb($breadcrumb);

// Try message
  drupal_set_message('Short status message 1', 'status');
  drupal_set_message('Short warning message 1', 'warning');
  drupal_set_message('Short error message 1', 'error');
  if (arg(1) == 'tab2') {
    drupal_set_message('Short status message 2', 'status');
    drupal_set_message('Short warning message 2', 'warning');
    drupal_set_message('Short error message 2', 'error');
  }
  if (arg(1) == 'tab3') {
    drupal_set_message('Long status message: <strong>Lorem ipsum dolor sit amet</strong>, consectetur adipiscing elit. Fusce eget sapien arcu, sed cursus turpis. Fusce sed convallis metus. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem.', 'status');
    drupal_set_message('Long warning message: <strong>Lorem ipsum dolor sit amet</strong>, consectetur adipiscing elit. Fusce eget sapien arcu, sed cursus turpis. Fusce sed convallis metus. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem.', 'warning');
    drupal_set_message('Long error message: <strong>Lorem ipsum dolor sit amet</strong>, consectetur adipiscing elit. Fusce eget sapien arcu, sed cursus turpis. Fusce sed convallis metus. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem.', 'error');
  }
// Try content
  $output = themetest_get_html();

// Try pager
  global $pager_total, $pager_page_array;
  $pager_total[0] = 200;

  if (arg(1) == 'tab2') {
    $pager_page_array[0] = 35;
  }
  if (arg(1) == 'tab3') {
    $pager_page_array[0] = 200;
  }

  $output .= theme('pager');
  return $output;
}

/**
 * Dummy form for testing.
 */
function themetest_form_test($form_state) {
  // form from Form Api quick start guide
  // http://drupal.org/node/751826

  // Access log settings:
  $options = array('1' => t('Enabled'), '0' => t('Disabled'));
  $form['access'] = array(
    '#type' => 'fieldset',
    '#title' => t('Access log settings'),
    '#tree' => TRUE,
  );
  $form['access']['log'] = array(
    '#type' => 'radios',
    '#title' => t('Log'),
    '#default_value' =>  variable_get('log', 0),
    '#options' => $options,
    '#description' => t('The log.'),
  );
  $period = drupal_map_assoc(array(3600, 10800, 21600, 32400, 43200, 86400, 172800, 259200, 604800, 1209600, 2419200, 4838400, 9676800), 'format_interval');
  $form['access']['timer'] = array(
    '#type' => 'select',
    '#title' => t('Discard logs older than'),
    '#default_value' => variable_get('timer', 259200),
    '#options' => $period,
    '#description' => t('The timer.'),
  );
  // Description
  $form['details'] = array(
    '#type' => 'fieldset',
    '#title' => t('Details'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['details']['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Describe it'),
    '#default_value' =>  variable_get('description', ''),
    '#cols' => 60,
    '#rows' => 5,
    '#description' => t('Log description.'),
  );
  $form['details']['admin'] = array(
    '#type' => 'checkbox',
    '#title' => t('Only admin can view'),
    '#default_value' => variable_get('admin', 0),
  );
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#size' => 30,
    '#maxlength' => 64,
    '#description' => t('Enter the name for this group of settings'),
  );
  $form['hidden'] = array('#type' => 'value', '#value' => 'is_it_here');
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  return $form;
}

/**
 * Dummy table for testing.
 */
function themetest_table($cols = 3, $rows = 3) {
  $header = array();
  for ($col = 1; $col <= $cols; $col++) {
    $header[] = 'Head '. $col;
  }
  $table_rows = array();
  for ($row = 1; $row <= $rows; $row++) {
    $table_row = array();
    for ($col = 1; $col <= $cols; $col++) {
      $table_row[] = 'Cell '. $col .'-'. $row;
    }
    $table_rows[] = $table_row;
  }
  return theme('table', $header, $table_rows, 'Table caption');
}

/**
 * Dummy HTML content for testing.
 */
function themetest_get_html() {

/* favorit of pp
    $output = <<<EOF
  <h1>Heading 1</h1>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <h2>Heading 2</h2>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <h3>Heading 3</h3>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <h4>Heading 4</h4>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <h5>Heading 5</h5>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <h6>Heading 6</h6>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <blockquote><p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p></blockquote>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <ol>
    <li>List item 1</li>
    <li>List item 2</li>
    <li>List item 3</li>
    <li>List item 4</li>
  </ol>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
  <ul>
    <li>List item 1</li>
    <li>List item 2</li>
    <li>List item 3</li>
    <li>List item 4</li>
  </ul>
  <p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Fusce <em>eget sapien arcu</em>, sed cursus turpis. <a href="http://drupal.org" title="Don't click me!">Fusce sed convallis metus</a>. Donec in libero sit amet nisl consectetur rutrum. Quisque commodo nunc eget lectus interdum porta. Ut nec rhoncus mi. Proin et justo tortor, vel fringilla lorem. Etiam ut enim justo. Integer aliquam, risus vitae ultrices feugiat, massa odio mattis ante, facilisis porta diam mauris bibendum nulla. Quisque scelerisque, erat vitae consectetur lacinia, mi ante malesuada massa, ut commodo ligula orci sed ligula. Nulla dapibus urna ipsum, sit amet varius mi. Proin nec erat eget nisl rutrum eleifend euismod non libero. Aenean dictum posuere quam nec convallis. Sed porttitor mauris vel metus laoreet nec convallis turpis convallis. </p>
EOF;
// */

// favorit of Jeff Noyes
    $output = <<<EOF
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>
<h3>paragraphs, body text and linebreaks</h3>
<p>Paragraph 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non erat odio, ut tristique nulla. Phasellus turpis urna, mattis non laoreet non, dictum quis leo.</p>
<p>Paragraph 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Linebreak: I feel a line break  (br) coming... <br /> ...up. Phasellus non erat odio, ut tristique nulla. Phasellus turpis urna, mattis non laoreet non, dictum quis leo.</p>
<p>Paragraph 3:Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non erat odio, ut tristique nulla. Phasellus turpis urna, mattis non laoreet non, dictum quis leo.</p>
<p>Linebreak: I feel a line break  (br) coming... <br /> ...up.</p>
<h3>Text treatments</h3>
<p><b>Bold text.</b><br /><i>Italic text.</i></p>
<h3>Quotes</h3>
<p>This is a blockquote:<br /></p><blockquote>Contents should not be swallowed. This is due to the enormous amount of harmful chemicals that has gone into this burger.</blockquote>
<h3>Images</h3>
<p><img src="http://www.jeffnoyes.com/non-drupal/milford_sound_t.jpg"></p>
<em>Pictures from site of Jeff Noyes :)</em>
<h3>Lists</h3>
<h2>Ordered list:</h2>
<ol><li>List item 1</li>
<li>List item 2</li>
<li>List item 3</li>
</ol><h2>Unordered list:</h2>
<ul><li>List item 1</li>
<li>List item 2</li>
<li>List item 3</li>
</ul><h2>Definition llist: </h2>
<dl><dt>Term 1</dt>
<dd>Definition of term 1</dd>
<dt>Term 2</dt>
<dd>Definition of term 2</dd>
</dl><h3>Tables</h3>
<table border="1"><thead><tr><th>Month</th>
<th>Savings</th>
</tr></thead><tfoot><tr><td>Sum</td>
<td>$180</td>
</tr></tfoot><tbody><tr><td>January</td>
<td>$100</td>
</tr><tr><td>February</td>
<td>$80</td>
</tr></tbody></table>
EOF;
// */

  return $output;
}
